### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by andersongns** [andersongns/adonis-backend#2]
- [ ] Cadastrar um Todo
- [ ] Marcar como Finalizado
- [ ] Remover um todo
